name: Go

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened  
      - synchronize
      - reopened

jobs:

  build:
    name: Build & Test 
    runs-on: ubuntu-latest
    env:
      GO111MODULE: auto
    steps:
    - name: Build
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Check out code 
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... 

    - name: Vet
      run: go vet -v ./...


